import { Router } from "express";
import { changePasswordHandler, forgotPassword, getCsrf, login, logout, me, register, resendVerification, resetPasswordHandler, verifyEmailHandler, } from "../controllers/auth.controller.js";
import { requireAuth } from "../middleware/auth.middleware.js";
import { csrfProtection } from "../middleware/csrf.middleware.js";
import { authRateLimiter, strictAuthRateLimiter, } from "../middleware/rateLimit.middleware.js";
import { validateBody } from "../middleware/validation.middleware.js";
import { changePasswordSchema, emailOnlySchema, loginSchema, registerSchema, resetPasswordSchema, verifyEmailSchema, } from "../validators/auth.validators.js";
const router = Router();
router.get("/csrf", getCsrf);
router.post("/register", authRateLimiter, csrfProtection, validateBody(registerSchema), register);
router.post("/login", authRateLimiter, csrfProtection, validateBody(loginSchema), login);
router.post("/logout", csrfProtection, requireAuth, logout);
router.get("/me", requireAuth, me);
router.post("/verify-email", strictAuthRateLimiter, csrfProtection, validateBody(verifyEmailSchema), verifyEmailHandler);
router.post("/resend-verification", strictAuthRateLimiter, csrfProtection, validateBody(emailOnlySchema), resendVerification);
router.post("/forgot-password", strictAuthRateLimiter, csrfProtection, validateBody(emailOnlySchema), forgotPassword);
router.post("/reset-password", strictAuthRateLimiter, csrfProtection, validateBody(resetPasswordSchema), resetPasswordHandler);
router.post("/change-password", authRateLimiter, csrfProtection, requireAuth, validateBody(changePasswordSchema), changePasswordHandler);
export default router;
//# sourceMappingURL=auth.routes.js.map